const express=require("express")
const {categoryController,getAllCategory,singleCategory,deleteCategory,updateCategory} = require("../../controllers/categoryController")
const { get } = require("mongoose")
const route= express.Router()
route.post("/createCategory",categoryController)
route.get("/getAllCategory",getAllCategory)
route.get("/singleCategory/:id",singleCategory)
route.delete("/deleteCategory/:id",deleteCategory)
route.patch("/updateCategory/:id",updateCategory)
module.exports=route